name: Kernel Builder
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 17 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Download scripts
        uses: actions/checkout@v2

      - name: clone clang
        run: wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/android-10.0.0_r3/clang-r353983c.tar.gz

      - name: extract tarball
        run: tar -xf clang-r353983c.tar.gz -C $(pwd)/clang

      - name: clone gcc
        run: git clone --depth=1 https://github.com/ZyCromerZ/aarch64-zyc-linux-gnu -b 12 gcc

      - name: clone gcc32
        run: git clone --depth=1 https://github.com/ZyCromerZ/arm-zyc-linux-gnueabi -b 12 gcc32

      - name: Deploy builder
        env:
          LINUXVER: ${{ secrets.LINUXVER}}
          DEVICE_DEFCONFIG: ${{ secrets.DEVICE_DEFCONFIG}}
          DEVICE_CODENAME: ${{ secrets.DEVICE_CODENAME}}
          KERNEL_NAME: ${{ secrets.KERNEL_NAME}}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_URL: ${{ secrets.GH_URL }}
        run: . build.sh
