name: Build Tetha Merlinx
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 17 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Download scripts
        uses: actions/checkout@v2

      - name: Deploy builder
        env:
          LINUXVER: ${{secrets.LINUXVER}}
          DEVICE_DEFCONFIG: merlin_defconfig
          DEVICE_CODENAME: Merlinx
          KERNEL_NAME: ${{secrets.KERNEL_NAME}}
          TG_TOKEN: ${{secrets.TG_TOKEN}}
          TG_CHAT_ID: ${{secrets.TG_CHAT_ID}}
          GH_USERNAME: ${{secrets.GH_USERNAME}}
          GH_EMAIL: ${{secrets.GH_EMAIL}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          GH_URL: ${{secrets.GH_URL}}
        run: cd merlinx && . tetha-merlinx.sh
